config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :donates
  end
  devise_for :accounts, controllers: {
    sessions: 'accounts/sessions',
    registrations: 'accounts/registrations',
    passwords: 'accounts/passwords',
    confirmations: 'accounts/confirmations'
  }

  namespace :admin do
    resources :dashboard do
      collection do
        get 'get_donations'
      end
    end
    resources :jobs
    resources :news
    resources :donations
    namespace :accounts do
      resources :alumnis do
        member do
          get :new_password
          put :change_password
        end
      end
      resources :companies do
        member do
          get :new_password
          put :change_password
        end
      end
      resources :faculties do
        member do
          get :new_password
          put :change_password
        end
      end
    end
  end

  namespace :accounts do
    resources :dashboard
    resources :jobs
    resources :news
  end

  resources :home
  resources :news
  resources :careers
  resources :donations

  root 'home#index'
end

app/views/shared/backend/_header.html.slim
header.main-header
  = link_to root_path, class: 'logo', target: '_blank' do
    span.logo-lg
      b
        | Home
  nav.navbar.navbar-static-top[role="navigation"]
    a.sidebar-toggle[href="#" data-toggle="offcanvas" role="button"]
      span.sr-only
        | Toggle navigation
    .navbar-custom-menu
      ul.nav.navbar-nav
        li.dropdown.user.user-menu
          a.dropdown-toggle[href="#" data-toggle="dropdown"]
            = image_tag('user.png', class: 'user-image', alt: "User Image")
            span.hidden-xs
              = current_account.email
          ul.dropdown-menu
            li.user-header
              = image_tag('user.png', class: 'img-circle', alt: "User Image")
              p
                Admin
            li.user-body
              .row
                .col-xs-4.text-center

                .col-xs-4.text-center

                .col-xs-4.text-center

            li.user-footer
              .pull-right
                = link_to "Sign Out", destroy_account_session_path, data: {method: 'DELETE'}, class: 'btn btn-default btn-flat'

app/views/shared/backend/_menu_sidebar.html.slim
li.header MAIN NAVIGATION
li class="#{is_active_path?('dashboard') ? 'active' : ''}"
  = link_to admin_dashboard_index_path do
    i.fa.fa-dashboard
    span Dashboard
- if current_account.has_role? :admin
  li class="treeview #{is_accounts_path?(params) ? 'active' : ''}"
    a href="#"
      i.fa.fa-user
      span Accounts
      i.fa.fa-angle-left.pull-right
    ul.treeview-menu class= "#{is_accounts_path?(params) ? 'menu-open' : ''}" style="#{is_accounts_path?(params) ? 'diplay:block;' : 'display:none;'}"
      li class="treeview #{is_accounts_path?(params) ? 'active' : ''}"
        a href="#{admin_accounts_alumnis_path}"
          i.fa.fa-group
          | Alumni
      li class="treeview #{is_accounts_path?(params) ? 'active' : ''}"
        a href="#{admin_accounts_companies_path}"
          i.fa.fa-building-o
          | Company
      li class="treeview #{is_accounts_path?(params) ? 'active' : ''}"
        a href="#{admin_accounts_faculties_path}"
          i.fa.fa-book
          | Faculty
  li class="#{is_active_path?('jobs') ? 'active' : ''}"
    = link_to admin_jobs_path do
      i.fa.fa-suitcase
      span Jobs
  li class="#{is_active_path?('news') ? 'active' : ''}"
    = link_to admin_news_index_path do
      i.fa.fa-newspaper-o
      span News
  li class="#{is_active_path?('donates') ? 'active' : ''}"
    = link_to admin_donates_path do
      i.fa.fa-money
      span Donates
- else
  li class="#{is_active_path?('jobs') ? 'active' : ''}"
    = link_to accounts_jobs_path do
      i.fa.fa-suitcase
      span Jobs

app/views/shared/backend/_navigation.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top[role="navigation"]
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'QuizMaster.', root_path, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      - unless user_signed_in?
        = form_for(:user, :url => session_path(:user)) do |f|
          ul.nav.navbar-nav[style="float: right"]
            li.login-field
              = f.email_field :email, class: 'form-control', placeholder: User.human_attribute_name(:email), autofocus: true
            li.login-field
              = f.password_field :password, class: 'form-control', placeholder: User.human_attribute_name(:password), autocomplete: 'off', value: nil
              = link_to "Forgot your password?", new_password_path(:user)
            li.login-field
              = f.submit 'Sign In', class: 'btn btn-info btn-block'

app/views/shared/backend/_sidebar.html.slim
aside.main-sidebar
  /! sidebar: style can be found in sidebar.less
  section.sidebar
    /! Sidebar user panel
    .user-panel
      .pull-left.image
        = image_tag('user.png', alt: 'User Image', class: 'img-circle')
      .pull-left.info
        p= current_account.email
        a href="#"
          i.fa.fa-circle.text-success
          | Online
    /! search form
    form.sidebar-form action="#" method="get"
      .input-group
        input.form-control name="q" placeholder="Search..." type="text" /
        span.input-group-btn
          button#search-btn.btn.btn-flat name="search" type="submit"
            i.fa.fa-search
    /! /.search form
    /! sidebar menu: : style can be found in sidebar.less
    ul.sidebar-menu
      = render 'shared/backend/menu_sidebar'