config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :donates
  end
  devise_for :accounts, controllers: {
    sessions: 'accounts/sessions',
    registrations: 'accounts/registrations',
    passwords: 'accounts/passwords',
    confirmations: 'accounts/confirmations'
  }

  namespace :admin do
    resources :dashboard do
      collection do
        get 'get_donations'
      end
    end
    resources :jobs
    resources :news
    resources :donations
    namespace :accounts do
      resources :alumnis do
        member do
          get :new_password
          put :change_password
        end
      end
      resources :companies do
        member do
          get :new_password
          put :change_password
        end
      end
      resources :faculties do
        member do
          get :new_password
          put :change_password
        end
      end
    end
  end

  namespace :accounts do
    resources :dashboard
    resources :jobs
    resources :news
  end

  resources :home
  resources :news
  resources :careers
  resources :donations

  root 'home#index'
end

app/views/shared/_footer.html.slim
footer.short.bg-secondary-1
  .container
    .row
      .col-sm-10
        span.sub= "© Copyright #{Date.today.strftime('%Y')} Adipati Kresna"
      .col-sm-2.text-right
        ul.social-icons
          li
            = link_to 'https://twitter.com/AlumniUPI', target: '_blank' do
              i.icon.social_twitter
          li
            = link_to 'https://www.facebook.com/AlumniUPI', target: '_blank' do
              i.icon.social_facebook

app/views/shared/_header.html.slim
nav.top-bar
  .container
    .row.utility-menu
      .col-sm-12
        .utility-inner.clearfix
          span.alt-font
            - if account_signed_in?
              | Hi #{current_account.display_name},
            | #{account_signed_in? ? 'Welcome to ' : ''} Portal Alumni Universitas Pendidikan Indonesia
          .pull-right
            - unless account_signed_in?
              = link_to 'Login', new_account_session_path, class: 'btn btn-primary login-button btn-xs'
              = link_to 'Signup', new_account_registration_path, class: 'btn btn-primary btn-filled btn-xs'
            - else
              = link_to 'Logout', destroy_account_session_path, data: {method: 'DELETE'}, class: 'btn btn-primary btn-xs'
    /! end of row
    .row.nav-menu
      .col-sm-4.col-md-2.columns
        = link_to root_path do
          = image_tag('logo-upi.png', alt: 'Logo', class: 'logo-upi')
      .col-sm-8.col-md-10.columns
        ul.menu
          li
            = link_to 'Beranda', root_path
          li
            = link_to 'Berita', news_index_path
          li
            = link_to 'Karir', careers_path
          - unless current_account && current_account.has_role?(:admin)
            li
              = link_to 'Donasi', donations_path
        ul.social-icons.text-right
          li
            = link_to 'https://twitter.com/AlumniUPI', target: '_blank' do
              i.icon.social_twitter
          li
            = link_to 'https://www.facebook.com/AlumniUPI', target: '_blank' do
              i.icon.social_facebook
    /! end of row
    .mobile-toggle
      i.icon.icon_menu
  /! end of container

app/views/shared/admin.html.slim
doctype html
html
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"]
    meta[name="description" content=""]
    meta[name="author" content=""]
    title
      | QuizMaster.
    script src="http://code.jquery.com/jquery-1.9.1.js"
    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'admin', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'icon_upi.ico'
  body.hold-transition.skin-blue.sidebar-mini
    = render "shared/admin/header"
    .wrapper.row-offcanvas.row-offcanvas-left
      aside.left-side.sidebar-offcanvas
        = render "shared/admin/sidebar"
      aside.right-side
        = yield(:content_header)
        - flash.each do |name, msg|
          .pad.margin.no-print
            = content_tag :div, :class => "alert alert-#{ name == "error" ? "danger" : "success" } alert-dismissable", :role => "alert" do
              button.close[type="button" data-dismiss="alert" aria-hidden="true"]
                | x
              = msg
        = yield
    .spinner.no-print.hidden
      = image_tag("ajax-loader.gif", alt: "")
    = javascript_include_tag 'application'
    - if params[:action] == 'show'
      script[async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBeGzAjIWncSEjQaPacmBHmPA8hdXWcnK0&callback=initMap"]
    = yield(:external_javascript)