config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :donates
  end
  devise_for :accounts, controllers: {
    sessions: 'accounts/sessions',
    registrations: 'accounts/registrations',
    passwords: 'accounts/passwords',
    confirmations: 'accounts/confirmations'
  }

  namespace :admin do
    resources :dashboard do
      collection do
        get 'get_donations'
      end
    end
    resources :jobs
    resources :news
    resources :donations
    namespace :accounts do
      resources :alumnis do
        member do
          get :new_password
          put :change_password
        end
      end
      resources :companies do
        member do
          get :new_password
          put :change_password
        end
      end
      resources :faculties do
        member do
          get :new_password
          put :change_password
        end
      end
    end
  end

  namespace :accounts do
    resources :dashboard
    resources :jobs
    resources :news
  end

  resources :home
  resources :news
  resources :careers
  resources :donations

  root 'home#index'
end

app/controllers/accounts/jobs_controller.rb
class Accounts::JobsController < Accounts::ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = JobVacancy.paginate(:page => params[:page], :per_page => 50)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = JobVacancy.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = JobVacancy.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to accounts_jobs_path, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to accounts_jobs_path, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to accounts_jobs_path, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = JobVacancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job_vacancy).permit(:position, :description, :due_date, :visible, :company_name, :level, :qualification, :salary_range_min, :salary_range_max, :location, :job_type, :negotiable_salary, :about_company)
    end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /admin/jobs
  # GET /admin/jobs.json
  def index
    @jobs = JobVacancy.paginate(:page => params[:page], :per_page => 50)
  end

  # GET /admin/jobs/1
  # GET /admin/jobs/1.json
  def show
  end

  # GET /admin/jobs/new
  def new
    @job = JobVacancy.new
  end

  # GET /admin/jobs/1/edit
  def edit
  end

  # POST /admin/jobs
  # POST /admin/jobs.json
  def create
    @job = JobVacancy.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to admin_jobs_path, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/jobs/1
  # PATCH/PUT /admin/jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to admin_jobs_path, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/jobs/1
  # DELETE /admin/jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to admin_jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = JobVacancy.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job_vacancy).permit(:position, :description, :due_date, :visible, :company_name, :level, :qualification, :salary_range_min, :salary_range_max, :location, :job_type, :negotiable_salary, :about_company)
    end
end

app/views/admin/jobs/_form.html.slim
- if @job.errors.any?
  .alert.alert-danger
    button.close[type="button" data-dismiss="alert" aria-hidden="true"]
      | ×
    = pluralize(@job.errors.count, 'error')
    |  encountered:
    ul
      - @job.errors.full_messages.each do |message|
        li
          = message
= simple_form_for @job, as: :job_vacancy, url: (@job.new_record? ? admin_jobs_path : admin_job_path(@job)), html: { class: 'form-horizontal', method: (@job.new_record? ? 'post' : 'put')} do |f|
  .panel-body
    .row
      .col-lg-12
        .col-md-6
          = f.input :position, label: 'Posisi', input_html: { class: 'form-control' }
      .col-lg-12
        .col-md-6
          = f.input :company_name, label: 'Nama Perusahaan', input_html: { class: 'form-control' }
      .col-lg-12
        .col-md-4
          = f.input :location, label: 'Lokasi', input_html: { class: 'form-control' }
      .col-lg-12
        .col-md-8
          = f.label :description, 'Deskripsi'
          = f.input :description, as: :text, label: false, input_html: { class: 'summernote' }
      .col-lg-12
        .col-md-4
          = f.input :level, label: 'Level Karir', as: :select, collection: JobVacancy::LEVEL, input_html: { class: 'form-control' }
        .col-md-4
          = f.input :qualification, label: 'Kualifikasi', as: :select, collection: JobVacancy::QUALIFICATION, input_html: { class: 'form-control' }
        .col-md-4
          = f.input :job_type, label: 'Tipe Pekerjaan', as: :select, collection: JobVacancy::JOBTYPE, input_html: { class: 'form-control' }
      .col-lg-12
        .col-md-4
          = f.input :salary_range_min, label: 'Gaji Minimum', as: :integer, input_html: { class: 'form-control', min: 0 }
        .col-md-4
          = f.input :salary_range_max, label: 'Gaji Maksimum', as: :integer, input_html: { class: 'form-control', min: 0 }
      .col-lg-12
        .col-md-2
          = f.input :negotiable_salary, label: 'Bisa Nego', as: :select, collection: JobVacancy::NEGOTIABLE, input_html: { class: 'form-control' }
      .col-lg-12
        .col-md-8
          = f.input :about_company, label: 'Tentang Perusahaan', as: :text, input_html: { class: 'form-control', rows: 8 }
      .col-lg-8
        .col-md-3
          = f.input :due_date, label: 'Tanggal Kadaluarsa', as: :string, input_html: { class: 'form-control due-date' }
        .col-md-2
          = f.input :visible, label: 'Tampilkan', as: :select, collection: JobVacancy::VISIBILITY , input_html: { class: 'form-control' }

  .panel-footer
    = link_to admin_jobs_path, class: 'btn btn-default' do
      i.fa.fa-undo Back
    = f.submit 'Save', class: 'btn btn-success'

app/views/admin/jobs/edit.html.slim
section.content-header
  h1
    |  Job
    small
      | Edit
  ol.breadcrumb
    li
      = link_to accounts_dashboard_index_path do
        i.fa.fa-dashboard
        |  Home
    li.active
      | Edit Job
section.content
  .row
    .col-xs-12
      .box
        .box-body
          = render 'form'

app/views/admin/jobs/index.html.slim
.row
  .col-md-12
    .box
      .box-header.with-border
        h3.box-title List Job
        .pull-right
          = link_to 'Add Job', new_admin_job_path, class: 'btn btn-success btn-md'
      /! /.box-header
      .box-body
        table.table.table-bordered
          tbody
            tr
              th style=("width: 10px") #
              th Posisi
              th Nama Perushaan
              th Deskripsi
              th Tanggal Kadaluarsa
              th Action
            - unless @jobs.blank?
              - @jobs.each do |job|
                tr
                  td= job.id
                  td= job.position
                  td= job.company_name
                  td= raw(job.description)
                  td= job.due_date
                  td
                    = link_to edit_admin_job_path(job) do
                      i.fa.fa-pencil
                    = link_to admin_job_path(job), data: {method: 'DELETE', confirm: 'Are you sure want to delete this job?'} do
                      i.fa.fa-trash-o
      /! /.box-body
      .box-footer.clearfix
        = will_paginate @jobs, renderer: BootstrapPagination::Rails

app/views/admin/jobs/new.html.slim
section.content-header
  h1
    |  Job
    small
      | New
  ol.breadcrumb
    li
      = link_to admin_dashboard_index_path do
        i.fa.fa-dashboard
        |  Home
    li.active
      | New Job
section.content
  .row
    .col-xs-12
      .box
        .box-body
          = render 'form'