config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :donates
  end
  devise_for :accounts, controllers: {
    sessions: 'accounts/sessions',
    registrations: 'accounts/registrations',
    passwords: 'accounts/passwords',
    confirmations: 'accounts/confirmations'
  }

  namespace :admin do
    resources :dashboard do
      collection do
        get 'get_donations'
      end
    end
    resources :jobs
    resources :news
    resources :donations
    namespace :accounts do
      resources :alumnis do
        member do
          get :new_password
          put :change_password
        end
      end
      resources :companies do
        member do
          get :new_password
          put :change_password
        end
      end
      resources :faculties do
        member do
          get :new_password
          put :change_password
        end
      end
    end
  end

  namespace :accounts do
    resources :dashboard
    resources :jobs
    resources :news
  end

  resources :home
  resources :news
  resources :careers
  resources :donations

  root 'home#index'
end

app/models/donate.rb
# == Schema Information
#
# Table name: donates
#
#  id             :integer          not null, primary key
#  amount         :decimal(, )
#  file_transfer  :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  recipient_name :string
#  valid          :boolean          default(FALSE)
#

class Donate < ActiveRecord::Base
  mount_uploader :file_transfer, ImageUploader

  validates_presence_of :amount, :file_transfer

  def self.get_json_data
    json = Donate.all.map{|donate| donate.as_json(except: [:id, :recipient_name, :updated_at, :file_transfer])}
    json.each_with_index do |j, index|
      json[index]['created_at'] = json[index]['created_at'].strftime('%Y-%m-%d')
      json[index]['amount'] = json[index]['amount'].to_i
    end
  end
end

app/controllers/admin/donates_controller.rb
class Admin::DonatesController < Admin::ApplicationController
  before_action :set_donate, only: [:show, :edit, :update, :destroy]

  # GET /admin/donates
  # GET /admin/donates.json
  def index
    @donates = Donate.all.paginate(page: params[:page], per_page: 30)
  end

  # GET /admin/donates/1
  # GET /admin/donates/1.json
  def show
  end

  # GET /admin/donates/new
  def new
    @donate = Donate.new
  end

  # GET /admin/donates/1/edit
  def edit
  end

  # POST /admin/donates
  # POST /admin/donates.json
  def create
    @donate = Donate.new(donate_params)

    respond_to do |format|
      if @donate.save
        format.html { redirect_to admin_donates_path, notice: 'Donate was successfully created.' }
        format.json { render :show, status: :created, location: @donate }
      else
        format.html { render :new }
        format.json { render json: @donate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/donates/1
  # PATCH/PUT /admin/donates/1.json
  def update
    respond_to do |format|
      if @donate.update(donate_params)
        format.html { redirect_to admin_donates_path, notice: 'Donate was successfully updated.' }
        format.json { render :show, status: :ok, location: @donate }
      else
        format.html { render :edit }
        format.json { render json: @donate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/donates/1
  # DELETE /admin/donates/1.json
  def destroy
    @donate.destroy
    respond_to do |format|
      format.html { redirect_to admin_donates_path, notice: 'Donate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donate
      @donate = Donate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donate_params
      params.require(:donate).permit(:recipient_name, :file_transfer, :amount)
    end
end

app/helpers/admin/donates_helper.rb
module Admin::DonatesHelper
end

app/views/admin/donates/_form.html.slim
- if @donate.errors.any?
  .alert.alert-danger
    button.close[type="button" data-dismiss="alert" aria-hidden="true"]
      | ×
    = pluralize(@donate.errors.count, 'error')
    |  encountered:
    ul
      - @donate.errors.full_messages.each do |message|
        li
          = message
= simple_form_for @donate, as: :donate, url: (@donate.new_record? ? admin_donates_path : admin_donate_path(@donate)), html: { class: 'form-horizontal', method: (@donate.new_record? ? 'post' : 'put')} do |f|
  .panel-body
    .row
      .col-lg-12
        .col-md-6
          = f.input :recipient_name, label: 'Nama', input_html: { class: 'form-control' }
      .col-lg-12
        .col-md-6
          = f.input :amount, label: 'Jumlah', as: :integer, input_html: { class: 'form-control', min: 0 }
        .col-md-4
          = f.input :file_transfer, as: :file, label: 'Bukti Transfer', input_html: { class: 'form-control' }

  .panel-footer
    = link_to admin_donates_path, class: 'btn btn-default' do
      i.fa.fa-undo Back
    = f.submit 'Save', class: 'btn btn-success'

app/views/admin/donates/edit.html.slim
section.content-header
  h1
    |  Donate
    small
      | Edit
  ol.breadcrumb
    li
      = link_to admin_dashboard_index_path do
        i.fa.fa-dashboard
        |  Home
    li.active
      | Edit Donate
section.content
  .row
    .col-xs-12
      .box
        .box-body
          = render 'form'

app/views/admin/donates/index.html.slim
.row
  .col-md-12
    .box
      .box-header.with-border
        h3.box-title List Donates
        .pull-right
          = link_to 'Add Donates', new_admin_donate_path, class: 'btn btn-success btn-md'
      /! /.box-header
      .box-body
        table.table.table-bordered
          tbody
            tr
              th style=("width: 10px") #
              th Nama
              th Jumlah
              th Bukti Transfer
              th Action
            - unless @donates.blank?
              - @donates.each do |donate|
                tr
                  td= donate.id
                  td= donate.recipient_name
                  td= number_to_currency(donate.amount, locale: :id)
                  td= image_tag(donate.file_transfer.thumb.url)
                  td
                    = link_to edit_admin_donate_path(donate) do
                      i.fa.fa-pencil
                    = link_to admin_donate_path(donate), data: {method: 'DELETE', confirm: 'Are you sure want to delete this donate?'} do
                      i.fa.fa-trash-o
      /! /.box-body
      .box-footer.clearfix
        = will_paginate @donates, renderer: BootstrapPagination::Rails

app/views/admin/donates/new.html.slim
section.content-header
  h1
    |  Donate
    small
      | New
  ol.breadcrumb
    li
      = link_to admin_dashboard_index_path do
        i.fa.fa-dashboard
        |  Home
    li.active
      | New Donate
section.content
  .row
    .col-xs-12
      .box
        .box-body
          = render 'form'